// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGbMqkxUObMKg-jis18Dl_MVVljboZvw',
    appId: '1:170173147800:web:8e3c6f129f2c5be004feed',
    messagingSenderId: '170173147800',
    projectId: 'my-pillar',
    authDomain: 'my-pillar.firebaseapp.com',
    storageBucket: 'my-pillar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtqmq7B_fAL_Oavx-js7PExa-g2PBe4I',
    appId: '1:170173147800:android:82c2223bf6c805e504feed',
    messagingSenderId: '170173147800',
    projectId: 'my-pillar',
    storageBucket: 'my-pillar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36UE3Vta6v1B4UmpMjKcQkVNGVZe9H1Y',
    appId: '1:170173147800:ios:54cccd38abb8846c04feed',
    messagingSenderId: '170173147800',
    projectId: 'my-pillar',
    storageBucket: 'my-pillar.firebasestorage.app',
    iosBundleId: 'com.pillar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB36UE3Vta6v1B4UmpMjKcQkVNGVZe9H1Y',
    appId: '1:170173147800:ios:54cccd38abb8846c04feed',
    messagingSenderId: '170173147800',
    projectId: 'my-pillar',
    storageBucket: 'my-pillar.firebasestorage.app',
    iosBundleId: 'com.pillar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUGbMqkxUObMKg-jis18Dl_MVVljboZvw',
    appId: '1:170173147800:web:ebde16b0b21ff2bf04feed',
    messagingSenderId: '170173147800',
    projectId: 'my-pillar',
    authDomain: 'my-pillar.firebaseapp.com',
    storageBucket: 'my-pillar.firebasestorage.app',
  );
}
